### ISSUE TITLE
Original Textures for The John Mod Reborn do not load in-game

### ISSUE THREAD

**Issue by Daralexen05** [Legodamen/The-John-Mod-Reborn#3]
Title says the problem. I have the 1.18.2 version of both the mod and texture pack. The original John textures do not load in-game no matter what I do.

**Comment by Legodamen** [comment]
Heyo. Sorry, I've been really busy and I forgot about checking this out.
Usually, I play test EVERYTHING. But this is one of those instances where I forgot to do so. Because the textures worked for 1.16.5, but I guess I never bothered to play test it for every version afterwards. Which is really weird because I could have sworn I did. But apparently entity textures got stored into a different file now. It's just textures>entities now. This change I guess happened somewhere after 1.16.5. 
So I guess for 1.18.2, 1.19.2, and 1.19.4 the texture pack just didn't work lol. 
Anyway, I went ahead and fixed it, and I uploaded new versions. It should work now and I'm sorry for the inconvenience.

https://www.curseforge.com/minecraft/texture-packs/the-john-mod-reborn-original-john-textures/files/4758521

**Comment by Daralexen05** [comment]
Thank you so much! I thought that I was doing something wrong. I am new to
modding Minecraft, because I always played the vanilla console versions
like Xbox 360, Wii U, New 3Ds XL, and Nintendo Switch. I love your mod so
much and I can’t wait to see how to Table of John’s is implemented. It’s a
core mod as part of my survival world, so I am glad that it’s still being
maintained.
