### ISSUE TITLE
Weeping John doesn't freeze

### ISSUE THREAD

**Issue by McSpy35** [Legodamen/The-John-Mod-Reborn#8]
Anytime the weeping john spawns it doesn't freeze when I look at it, it just runs at me

**Comment by Legodamen** [comment]
What version of the mod and game version do you have?

**Comment by Daralexen05** [comment]
> Anytime the weeping john spawns it doesn't freeze when I look at it, it just runs at me

It has to be very specific. I think the cursor has to be on its weird mouth stomach to count as "looking" at it.

**Comment by McSpy35** [comment]
The game version is 1.19.2 and the mod version is 1.0.5

**Comment by McSpy35** [comment]
> What version of the mod and game version do you have?

The game version is 1.19.2 and the mod version is 1.0.5

**Comment by Legodamen** [comment]
I just tweaked the radius of the distance you have to be from the john for him to run at you, Before it was 10 blocks. Now it's as far as they can see you. So 20-25+
Also you have to be looking at it directly, cursor/crosshair over any part of it for him to stop moving. This is by design.
But either way, I will be a minor update soon for the "distance" tweak. for 1.19.2 1.0.6.

**Comment by Legodamen** [comment]
Fixed the issues in new update. Anything else comes up, feel free to open a Issue.
Thanks!

https://www.curseforge.com/minecraft/mc-mods/the-john-mod-reborn/files/4956325
